// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"patungan_app_echo/internal/models"
	"patungan_app_echo/internal/modules/user"
	"patungan_app_echo/internal/template/layouts"
	types "patungan_app_echo/internal/template/types"
)

// UserFormProps contains props for the user form page
type UserFormProps struct {
	Title       string
	ActiveNav   string
	Breadcrumbs []types.Breadcrumb
	UserEmail   string
	UserUID     string
	IsEdit      bool
	User        *user.UserSummary
}

// UserForm renders the user create/edit form
func UserForm(props UserFormProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Header --> <div class=\"flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6\"><div><h1 class=\"text-xl md:text-2xl font-bold text-text-primary tracking-tight\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.IsEdit {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "Edit User")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "Create New User")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h1><p class=\"text-xs md:text-sm text-text-secondary mt-0.5\">Manage member account details and permissions</p></div><a href=\"/admin/users\" class=\"inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border text-xs font-semibold text-text-secondary hover:text-text-primary hover:bg-bg-hover transition-colors\"><i data-lucide=\"arrow-left\" class=\"w-3.5 h-3.5\"></i> Back to Users</a></div><!-- Form Card --> <div class=\"w-full bg-bg-card rounded-xl border border-border shadow-card p-6 sm:p-8\"><form method=\"POST\" action=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(userFormAction(props.IsEdit, props.User))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/admin/user/user_form.templ`, Line: 53, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"space-y-5\"><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div><label class=\"block mb-1.5 text-xs font-semibold text-text-secondary uppercase tracking-wider\">Full Name</label> <input type=\"text\" name=\"name\" placeholder=\"e.g. John Doe\" class=\"w-full px-3.5 py-2 rounded-lg border border-border bg-input-bg text-text-primary text-sm focus:outline-none focus:ring-1 focus:ring-primary placeholder:text-text-muted\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/admin/user/user_form.templ`, Line: 62, Col: 30}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" required></div><div><label class=\"block mb-1.5 text-xs font-semibold text-text-secondary uppercase tracking-wider\">Email Address</label> <input type=\"email\" name=\"email\" placeholder=\"john@example.com\" class=\"w-full px-3.5 py-2 rounded-lg border border-border bg-input-bg text-text-primary text-sm focus:outline-none focus:ring-1 focus:ring-primary font-mono placeholder:text-text-muted\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Email)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/admin/user/user_form.templ`, Line: 73, Col: 31}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" required></div><div><label class=\"block mb-1.5 text-xs font-semibold text-text-secondary uppercase tracking-wider\">Phone Number (Optional)</label> <input type=\"tel\" name=\"phone\" placeholder=\"628123456789\" class=\"w-full px-3.5 py-2 rounded-lg border border-border bg-input-bg text-text-primary text-sm focus:outline-none focus:ring-1 focus:ring-primary font-mono placeholder:text-text-muted\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Phone)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/admin/user/user_form.templ`, Line: 84, Col: 31}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\"></div><div><label class=\"block mb-1.5 text-xs font-semibold text-text-secondary uppercase tracking-wider\">User Role</label> <select name=\"user_type\" class=\"w-full px-3.5 py-2 rounded-lg border border-border bg-bg-card text-text-primary text-xs focus:outline-none focus:ring-1 focus:ring-primary\"><option value=\"Member\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.User.UserType == "" || props.User.UserType == string(models.UserTypeMember) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, ">Member</option> <option value=\"Admin\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.User.UserType == string(models.UserTypeAdmin) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, ">Admin</option></select></div></div><div class=\"pt-4 flex flex-col sm:flex-row gap-2.5 border-t border-border/60\"><button type=\"submit\" class=\"inline-flex justify-center items-center gap-2 px-5 py-2 rounded-lg font-semibold transition-colors bg-primary text-white hover:bg-primary-hover text-xs shadow-xs cursor-pointer\"><i data-lucide=\"check\" class=\"w-4 h-4\"></i> Save User</button> <a href=\"/admin/users\" class=\"inline-flex justify-center items-center gap-2 px-4 py-2 rounded-lg border border-border font-semibold no-underline transition-colors bg-bg-card text-text-secondary hover:text-text-primary hover:bg-bg-hover text-xs\">Cancel</a></div></form></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(layouts.BaseProps{
			Title:       props.Title,
			ActiveNav:   props.ActiveNav,
			Breadcrumbs: props.Breadcrumbs,
			UserEmail:   props.UserEmail,
			UserUID:     props.UserUID,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Helper function to generate user form action URL
func userFormAction(isEdit bool, u *user.UserSummary) templ.SafeURL {
	if isEdit {
		return templ.SafeURL(fmt.Sprintf("/admin/users/%d/update", u.ID))
	}
	return templ.SafeURL("/admin/users")
}

var _ = templruntime.GeneratedTemplate
