// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package settings

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"patungan_app_echo/internal/models"
	settings "patungan_app_echo/internal/modules/settings"
	"patungan_app_echo/internal/template/layouts"
	types "patungan_app_echo/internal/template/types"
)

type PaymentSettingsProps struct {
	Title       string
	ActiveNav   string
	Breadcrumbs []types.Breadcrumb
	UserEmail   string
	UserUID     string
	Settings    settings.View
}

func PaymentSettings(props PaymentSettingsProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full\"><div class=\"mb-6\"><h1 class=\"text-xl md:text-2xl font-bold text-text-primary tracking-tight\">Application Settings</h1><p class=\"text-xs md:text-sm text-text-secondary mt-0.5\">Manage payment gateways and global configurations</p></div><form action=\"/admin/settings\" method=\"POST\" class=\"space-y-6\"><!-- Active Gateway Selection --><div class=\"bg-bg-card rounded-xl border border-border overflow-hidden shadow-card\"><div class=\"p-4 border-b border-border bg-bg-subtle/50\"><h3 class=\"text-sm font-bold text-text-primary flex items-center gap-2\"><i data-lucide=\"sliders\" class=\"w-4 h-4 text-text-secondary\"></i> General Settings</h3></div><div class=\"p-5\"><label class=\"block text-xs font-semibold text-text-secondary uppercase tracking-wider mb-2\">Active Payment Gateway</label> <select name=\"active_payment_gateway\" class=\"w-full px-3.5 py-2 bg-bg-body border border-border rounded-lg text-text-primary text-xs focus:outline-none focus:ring-1 focus:ring-primary transition-colors max-w-md\"><option value=\"midtrans\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Settings.ActiveGateway == string(models.PaymentGatewayMidtrans) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ">Midtrans</option> <option value=\"mayar\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Settings.ActiveGateway == string(models.PaymentGatewayMayar) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, ">Mayar.id</option></select><p class=\"mt-1.5 text-[11px] text-text-muted\">This gateway will be used for all new payment initiations by default.</p></div></div><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><!-- Midtrans Configuration --><div class=\"bg-bg-card rounded-xl border border-border overflow-hidden shadow-card\"><div class=\"p-4 border-b border-border bg-bg-subtle/50\"><h3 class=\"text-sm font-bold text-text-primary flex items-center gap-2\"><i data-lucide=\"credit-card\" class=\"w-4 h-4 text-text-secondary\"></i> Midtrans</h3></div><div class=\"p-5 space-y-3.5\"><div><label class=\"block text-xs font-semibold text-text-secondary uppercase tracking-wider mb-1\">Merchant ID</label> <input type=\"text\" name=\"midtrans_merchant_id\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(props.Settings.MidtransMerchantID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/admin/settings/payment_settings.templ`, Line: 70, Col: 50}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"w-full px-3.5 py-2 bg-bg-body border border-border rounded-lg text-text-primary text-xs focus:outline-none focus:ring-1 focus:ring-primary font-mono\" placeholder=\"e.g. G123456789\"></div><div x-data=\"{ show: false }\"><label class=\"block text-xs font-semibold text-text-secondary uppercase tracking-wider mb-1\">Server Key</label><div class=\"relative\"><input :type=\"show ? 'text' : 'password'\" name=\"midtrans_server_key\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(props.Settings.MidtransServerKey)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/admin/settings/payment_settings.templ`, Line: 81, Col: 50}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" class=\"w-full px-3.5 py-2 bg-bg-body border border-border rounded-lg text-text-primary text-xs focus:outline-none focus:ring-1 focus:ring-primary font-mono pr-9\"> <button type=\"button\" @click=\"show = !show\" class=\"absolute right-2.5 top-1/2 -translate-y-1/2 text-text-muted hover:text-text-primary transition-colors\"><i :data-lucide=\"show ? 'eye-off' : 'eye'\" class=\"w-3.5 h-3.5\"></i></button></div></div><div><label class=\"block text-xs font-semibold text-text-secondary uppercase tracking-wider mb-1\">Client Key</label> <input type=\"text\" name=\"midtrans_client_key\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(props.Settings.MidtransClientKey)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/admin/settings/payment_settings.templ`, Line: 98, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" class=\"w-full px-3.5 py-2 bg-bg-body border border-border rounded-lg text-text-primary text-xs focus:outline-none focus:ring-1 focus:ring-primary font-mono\"></div><div class=\"flex items-center gap-2.5 pt-1\"><input type=\"checkbox\" id=\"midtrans_is_production\" name=\"midtrans_is_production\" value=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Settings.MidtransIsProduction {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " checked")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, " class=\"w-4 h-4 rounded border-border text-primary focus:ring-primary\"> <label for=\"midtrans_is_production\" class=\"text-xs font-medium text-text-primary cursor-pointer select-none\">Enable Production Mode</label></div></div></div><!-- Mayar Configuration --><div class=\"bg-bg-card rounded-xl border border-border overflow-hidden shadow-card\"><div class=\"p-4 border-b border-border bg-bg-subtle/50\"><h3 class=\"text-sm font-bold text-text-primary flex items-center gap-2\"><i data-lucide=\"zap\" class=\"w-4 h-4 text-amber-600\"></i> Mayar.id</h3></div><div class=\"p-5 space-y-3.5\"><div x-data=\"{ show: false }\"><label class=\"block text-xs font-semibold text-text-secondary uppercase tracking-wider mb-1\">API Key</label><div class=\"relative\"><input :type=\"show ? 'text' : 'password'\" name=\"mayar_api_key\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(props.Settings.MayarAPIKey)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/admin/settings/payment_settings.templ`, Line: 131, Col: 44}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" class=\"w-full px-3.5 py-2 bg-bg-body border border-border rounded-lg text-text-primary text-xs focus:outline-none focus:ring-1 focus:ring-primary font-mono pr-9\"> <button type=\"button\" @click=\"show = !show\" class=\"absolute right-2.5 top-1/2 -translate-y-1/2 text-text-muted hover:text-text-primary transition-colors\"><i :data-lucide=\"show ? 'eye-off' : 'eye'\" class=\"w-3.5 h-3.5\"></i></button></div></div><div class=\"flex items-center gap-2.5 pt-1\"><input type=\"checkbox\" id=\"mayar_is_production\" name=\"mayar_is_production\" value=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.Settings.MayarIsProduction {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " checked")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " class=\"w-4 h-4 rounded border-border text-primary focus:ring-primary\"> <label for=\"mayar_is_production\" class=\"text-xs font-medium text-text-primary cursor-pointer select-none\">Enable Production Mode</label></div></div></div></div><div class=\"flex justify-end pt-2\"><button type=\"submit\" class=\"px-5 py-2 bg-primary text-white text-xs font-semibold rounded-lg hover:bg-primary-hover transition-colors shadow-xs cursor-pointer flex items-center gap-1.5\"><i data-lucide=\"check\" class=\"w-4 h-4\"></i> Save Settings</button></div></form></div><script>\n\t\t\t// Re-initialize lucide icons when Alpine.js toggles them\n\t\t\tdocument.addEventListener('alpine:init', () => {\n\t\t\t\tAlpine.effect(() => {\n\t\t\t\t\tsetTimeout(() => lucide.createIcons(), 0);\n\t\t\t\t});\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(layouts.BaseProps{
			Title:       props.Title,
			ActiveNav:   props.ActiveNav,
			Breadcrumbs: props.Breadcrumbs,
			UserEmail:   props.UserEmail,
			UserUID:     props.UserUID,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
